server:
  port: 8889

spring:
  application:
    name: es
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&nullCatalogMeansCurrent=true&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
mybatis-plus:
  mapper-locations: classpath:mapping/**/*Mapping.xml
  type-aliases-package: com.snow.easyexcel.entity

#showSql
logging:
  level:
    com:
      snow:
        learn:
          mapper: debug
